# Generated by Django 3.2.11 on 2022-01-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maintenances', to='vehicle.component')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.maintenance')),
            ],
        ),
    ]
