name: Linters

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: flake8
        uses: py-actions/flake8@v2
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: isort
        uses: isort/isort-action@v0.1.0
        with:
          sortPaths: grage
